apiVersion: v1
kind: Namespace
metadata:
  name: test-team-two
  labels:
    company: mycompany
    department: mydepartment
    application: app
    owner: myteamone
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ns-owner-binding
  namespace: test-team-two
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  namespace: test-team-two
  name: '7345435-345345-45-55555555'
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
spec:
  limits:
  - default:
      cpu: "200m"
      memory: 512Mi
    defaultRequest:
      cpu: "200m"
      memory: 256Mi
    max:
      cpu: "1000m"
      memory: 3Gi
    min:
      cpu: "200m"
      memory: 256Mi
    type: Container
