apiVersion: v1
kind: Namespace
metadata:
  name: co-ingress
  labels:
    owner: {{.labelowner}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: co-monitoring
  labels:
    owner: {{.labelowner}}
---
