kind: Service
apiVersion: v1
metadata:
  name: co-prometheus-kube-prometh-nginx-ingress
  namespace: co-ingress
  labels:
    app: ingress-nginx
    release: co-prometheus
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
  - name: metrics
    port: 10254
---
kind: Service
apiVersion: v1
metadata:
  name: co-prometheus-kube-prometh-nginx-ingress
  namespace: co-ingress-internal
  labels:
    app: ingress-nginx
    release: co-prometheus
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
  - name: metrics
    port: 10254
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller-metrics
  namespace: co-ingress
  labels:
    app: ingress-nginx
    release: co-prometheus
spec:
  endpoints:
  - port: metrics
    interval: 15s
  selector:
    matchLabels:
      app: ingress-nginx
  namespaceSelector:
    matchNames:
    - co-ingress
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller-metrics
  namespace: co-ingress-internal
  labels:
    app: ingress-nginx
    release: co-prometheus
spec:
  endpoints:
  - port: metrics
    interval: 15s
  selector:
    matchLabels:
      app: ingress-nginx
  namespaceSelector:
    matchNames:
    - co-ingress-internal
---
