---
apiVersion: v1
kind: Namespace
metadata:
  name: co-ingress
  labels:
    name: co-ingress
    owner: cloud-operations
---
apiVersion: v1
kind: Namespace
metadata:
  name: co-ingress-internal
  labels:
    name: co-ingress-internal
    owner: cloud-operations
---
apiVersion: v1
kind: Namespace
metadata:
  name: co-monitoring
  labels:
    name: co-monitoring
    owner: cloud-operations
---
apiVersion: v1
kind: Namespace
metadata:
  name: co-maintenance
  labels:
    name: co-maintenance
    owner: cloud-operations
---
apiVersion: v1
kind: Namespace
metadata:
  name: co-opa
  labels:
    name: co-opa
    owner: cloud-operations
---