apiVersion: v1
kind: Namespace
metadata:
  name: co-specific-rancher
  labels:
    owner: 
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
spec:
  limits:
  - default:
      cpu: "200m"
      memory: 512Mi
    defaultRequest:
      cpu: "200m"
      memory: 256Mi
    max:
      cpu: "1000m"
      memory: 2Gi
    min:
      cpu: "200m"
      memory: 256Mi
    type: Container
