apiVersion: v1
kind: Namespace
metadata:
  name: test-team-two
  labels:
    company: mycompany
    department: mydepartment
    application: app
    owner: myteamone
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ns-owner-binding
  namespace: test-team-two
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  namespace: test-team-two
  name: '7345435-345345-45-55555555'
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-high
    namespace: test-team-two
  spec:
    hard:
      cpu: "10"
      memory: 200Gi
      pods: "10"
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["high"]
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-medium
    namespace: test-team-two
  spec:
    hard:
      cpu: "5"
      memory: 20Gi
      pods: "10"
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["medium"]
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-low
    namespace: test-team-two
  spec:
    hard:
      cpu: "1"
      memory: 10Gi
      pods: "10"
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["low"]
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: object-quota
    namespace: test-team-two
  spec:
    hard:
      pods: 50
      persistentvolumeclaims: 10
      replicationcontrollers: 0
      resourcequotas: 1
      services: 20
      services.loadbalancers: 0
      services.nodeports: 0