apiVersion: v1
kind: Namespace
metadata:
  name: co-specific-azure
  labels:
    owner: cloud-ops
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
spec:
  limits:
  - default:
      cpu: "200m"
      memory: 512Mi
    defaultRequest:
      cpu: "200m"
      memory: 256Mi
    max:
      cpu: "2000m"
      memory: 4Gi
    min:
      cpu: "200m"
      memory: 256Mi
    type: Container
