apiVersion: v1
kind: Namespace
metadata:
  name: co-specific-azure
  labels:
    owner: cloud-ops
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
spec:
  limits:
  - max:
      cpu: "2000m"
      memory: 4Gi
    min:
      cpu: "100m"
      memory: "90Mi"
    default:
      cpu: "700m"
      memory: "900Mi"
    defaultRequest:
      cpu: "110m"
      memory: "111Mi"
    type: Container
