kind: Service
apiVersion: v1
metadata:
  name: co-prometheus-kube-prometh-nginx-ingress
  namespace: {{.nginx.service.namespace}}
  labels:
    app: ingress-nginx
    release: co-prometheus
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
  - name: {{.nginx.service.name}}
    port: {{.nginx.service.port}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller-metrics
  namespace: {{.nginxservicemonitor.namespace}}
  labels:
    app: ingress-nginx
    release: co-prometheus
spec:
  endpoints:
  - port: {{.nginxservicemonitor.port}}
    interval: {{.nginxservicemonitor.interval}}
  selector:
    matchLabels:
      app: ingress-nginx
  namespaceSelector:
    matchNames:
    - {{.nginx.service.namespace}}