apiVersion: v1
kind: Namespace
metadata:
  name: {{.namespace}}
  labels:
    company: {{.labelcompany}}
    department: {{.labeldepartment}}
    application: {{.labelapplication}}
    owner: {{.labelowner}}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ns-owner-binding
  namespace: {{.namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: Group
  namespace: {{.namespace}}
  name: '{{.groupid}}'
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
spec:
  limits:
  - default:
      cpu: "200m"
      memory: 512Mi
    defaultRequest:
      cpu: "200m"
      memory: 256Mi
    max:
      cpu: "{{.limitsmaxcpu}}"
      memory: {{.limitsmaxmem}}
    min:
      cpu: "200m"
      memory: 256Mi
    type: Container
---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-high
    namespace: {{.namespace}}
  spec:
    hard:
      cpu: "10"
      memory: 200Gi
      pods: "10"
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["high"]
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-medium
    namespace: {{.namespace}}
  spec:
    hard:
      cpu: "5"
      memory: 20Gi
      pods: "10"
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["medium"]
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: pods-low
    namespace: {{.namespace}}
  spec:
    hard:
      cpu: "1"
      memory: 10Gi
      pods: "10"
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["low"]
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: object-quota
    namespace: {{.namespace}}
  spec:
    hard:
      pods: {{.resourcequota.pods}}
      persistentvolumeclaims: {{.resourcequota.persistentvolumeclaims}}
      replicationcontrollers: {{.resourcequota.replicationcontrollers}}
      resourcequotas: {{.resourcequota.resourcequotas}}
      services: {{.resourcequota.services}}
      services.loadbalancers: {{.resourcequota.servicesloadbalancers}}
      services.nodeports: {{.resourcequota.servicesnodeports}}