---
apiVersion: v1
kind: Namespace
metadata:
  name: co-ingress
  labels:
    name: co-ingress
    owner: {{.labels.owner}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: co-ingress-internal
  labels:
    name: co-ingress-internal
    owner: {{.labels.owner}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: co-monitoring
  labels:
    name: co-monitoring
    owner: {{.labels.owner}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: co-opa
  labels:
    name: co-opa
    owner: {{.labels.owner}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: co-maintenance
  labels:
    name: co-maintenance
    owner: {{.labels.owner}}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
spec:
  privileged: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: unprivileged
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'