kind: Service
apiVersion: v1
metadata:
  name: co-prometheus-kube-prometh-nginx-ingress
  namespace: co-ingress
  labels:
    app: ingress-nginx
    release: co-prometheus
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
  - name: {{.nginx.service.name}}
    port: {{.nginx.service.port}}
---
kind: Service
apiVersion: v1
metadata:
  name: co-prometheus-kube-prometh-nginx-ingress
  namespace: co-ingress-internal
  labels:
    app: ingress-nginx
    release: co-prometheus
spec:
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
  - name: {{.nginx.service.name}}
    port: {{.nginx.service.port}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress-controller-metrics
  namespace: co-monitoring
  labels:
    app: ingress-nginx
    release: co-prometheus
spec:
  endpoints:
  - port: {{.nginx.servicemonitor.port}}
    interval: {{.nginx.servicemonitor.interval}}
  selector:
    matchLabels:
      app: ingress-nginx
  namespaceSelector:
    matchNames:
    - co-ingress
    - co-ingress-internal