apiVersion: v1
kind: Namespace
metadata:
  name: co-specific-{{.cloudprovider}}
  labels:
    owner: {{.labels.owner}}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
spec:
  limits:
  - max:
      cpu: "{{.limitsmaxcpu}}"
      memory: {{.limitsmaxmem}}
    min:
      cpu: "100m"
      memory: "90Mi"
    default:
      cpu: "700m"
      memory: "900Mi"
    defaultRequest:
      cpu: "110m"
      memory: "111Mi"
    type: Container
